### ISSUE TITLE
请问，最新版本的问题

### ISSUE THREAD

**Issue by hclasmn** [zerofo/zerofo.github.io#1]
![image](https://user-images.githubusercontent.com/32213103/93464574-f2227880-f91b-11ea-9bca-d38ef30bbb9e.png)
如图提示，然后跳转你的网站，非常慢，

**Comment by hclasmn** [comment]
![image](https://user-images.githubusercontent.com/32213103/93464628-0bc3c000-f91c-11ea-9edd-8673db3eafcc.png)

**Comment by zerofo** [comment]
你直接换源吧。跳转要10秒呢
